"""update relationships between Set and Exercise

Revision ID: 2fdcc079a0df
Revises: 9b51be05ed3b
Create Date: 2026-07-06 17:30:58.614620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fdcc079a0df'
down_revision: Union[str, Sequence[str], None] = '9b51be05ed3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
