"""add workouts, sets

Revision ID: 9b51be05ed3b
Revises: 03649e8c3c88
Create Date: 2026-06-30 17:00:09.081461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b51be05ed3b'
down_revision: Union[str, Sequence[str], None] = '03649e8c3c88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('bodyweight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('performed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('exercise', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('sets')
    op.drop_table('workout')
    # ### end Alembic commands ###
